### PR TITLE
Update nil compare

### PR DESCRIPTION
**Pull request by chipsnyder**
@MichaelCampbell @hkellaway @OatLiew @tsivilay 

Updated text to handle nil comparison. This came up in a recent PR and needed to be updated here

### CODE REVIEW

**Comment by tsivilay** [comment]
:+1:

**Comment by hkellaway** [comment]
:+1:

**Comment by MichaelCampbell** [comment]
:+1:

**Comment by MichaelCampbell** [comment]
@OatLiew all yours

**Comment by OatLiew** [comment]
:+1:

**Pull request merged**
